#pragma once

#ifndef NOMINMAX
#define NOMINMAX
#endif


//player
#define ANIM_SPEED          150
#define MOVE_SPEED          10

//Draw_Scale
#define DRAW_SCALE          3
#define UI_BAR_DRAW_SCALE   5
#define NPC_SHOPKEEPER_DRAW_SCALE 4

//ScreenSize
#define SCREEN_WIDTH        1280
#define SCREEN_HEIGHT       800

//Monster
#define MONSTER_SKELETON_SCR_X 24
#define MONSTER_SKELETON_SCR_Y 32
#define MONSTER_SKELETON_POS_X 0
#define MONSTER_SKELETON_POS_Y 0
#define MONSTER_BAT_SCR_X 23 
#define MONSTER_BAT_SCR_Y 24 
#define MONSTER_BAT_POS_X 0
#define MONSTER_BAT_POS_Y 0
#define MONSTER_SLIME_SCR_X 27 
#define MONSTER_SLIME_SCR_Y 26
#define MONSTER_SLIME_POS_X 0
#define MONSTER_SLIME_POS_Y 0


//UI Pos
#define UI_HP_POS_X			1040
#define UI_HP_POS_Y			10
#define UI_MONEY_POS_X		1120
#define UI_MONEY_POS_Y		10
#define UI_JEWEL_POS_X		1120
#define UI_JEWEL_POS_Y		90
#define UI_INVEN_POS_X		20
#define UI_INVEN_POS_Y		10
#define UI_ITEM_POS_X		20
#define UI_ITEM_POS_Y		110
#define UI_RHYTHM_HEART_POS_X	640
#define UI_RHYTHM_HEART_POS_Y	650
#define UI_RHYTHM_BAR_POS_X 640
#define UI_RHYTHM_BAR_POS_Y 650
#define UI_MONEY_FONT_POS_X	1180
#define UI_MONEY_FONT_POS_Y	48
#define UI_JEWEL_FONT_POS_X	1180
#define UI_JEWEL_FONT_POS_Y	118

//Map Size
#define MAP_WIDTH           60
#define MAP_HEIGHT          40

//Tile Frame
#define TILE_DEFAULT_X      48
#define TILE_DEFAULT_Y      0

//Wall Frame
#define WALL_DEFAULT_X      0
#define WALL_DEFAULT_Y      0
#define WALL_HARD_X         696
#define WALL_HARD_Y         0
#define WALL_BADROCK_X      120
#define WALL_BADROCK_Y      288
#define WALL_SHOP_X         0
#define WALL_SHOP_Y         288
#define WALL_DEFAULT_RANGE  15     

//UI_Sprtie_Pos
#define UI_HP_SCR_X 0
#define UI_HP_SCR_Y 0
#define UI_NULL_HP_SCR_X 58
#define UI_NULL_HP_SCR_Y 0
#define UI_MONEY_SCR_X 85
#define UI_MONEY_SCR_Y 24
#define UI_JEWEL_SCR_X 88
#define UI_JEWEL_SCR_Y 0
#define UI_RHYTHM_HEART_SCR_X 115
#define UI_RHYTHM_HEART_SCR_Y 0
#define UI_RHYTHM_BAR_SCR_X 200
#define UI_RHYTHM_BAR_SCR_Y 9

//UI_Frame
#define FRAME_SIZE          24
#define UI_DRAW_SCALE 1.5f
#define UI_INVEN_FRAME_X 31
#define UI_INVEN_FRAME_Y 40
#define UI_GAP   4.0f
#define UI_INVEN_PNG_X   0
#define UI_INVEN_PNG_Y   51
#define UI_ITEM_GAP_Y 8.0f
#define UI_ITEM_PNG_X 0
#define UI_ITEM_PNG_Y 96
#define UI_ITEM_FRAME_PNG_X 31
#define UI_ITEM_FRAME_PNG_Y 35
#define UI_RHYTHM_HEART_FRAME_X 41
#define UI_RHYTHM_HEART_FRAME_Y 50
#define UI_RHYTHM_BAR_FRAME_X 7
#define UI_RHYTHM_BAR_FRAME_Y 31

//NPC_Frame
#define NPC_SHOPKEEPER_FRAME_X 47
#define NPC_SHOPKEEPER_FRAME_Y 39

//Rhythm
#define RHYTHM_BPM 120
#define RHYTHM_MARGIN	0.3f

//Item_Frame
#define ITEM_ARMOR_FRAME 26
#define ITEM_FOOTWEAR_FRAME 26
#define ITEM_HEADWEAR_FRAME 26
#define ITEM_SHOVEIS_FRAME_X 29
#define ITEM_SHOVEIS_FRAME_Y 26
#define ITEM_TORCH_FRAME_X 20
#define ITEM_TORCH_FRAME_Y 26
#define ITEM_WEAPON_DAGGER_FRAME_X 16
#define ITEM_WEAPON_DAGGER_FRAME_Y 18
#define ITEM_WEAPON_LONGSWORD_FRAME_X 29
#define ITEM_WEAPON_LONGSWORD_FRAME_Y 24
#define ITEM_WEAPON_RAPIER_FRAME_X 29
#define ITEM_WEAPON_RAPIER_FRAME_Y 25
#define ITEM_GOLD_FRAME 24
#define ITEM_BOMB_FRAME 24
#define ITEM_CONSUMABLE_FRAME 24

//item pos
#define ITEM_WEAPON_DAGGER_SCR_X 0
#define ITEM_WEAPON_DAGGER_SCR_Y 0
#define ITEM_WEAPON_LONGSWORD_SCR_X 0
#define ITEM_WEAPON_LONGSWORD_SCR_Y 54
#define ITEM_WEAPON_RAPIER_SCR_X 0
#define ITEM_WEAPON_RAPIER_SCR_Y 115
#define ITEM_GOLD_SCR_X 0
#define ITEM_GOLD_SCR_Y 0
#define ITEM_BOMB_SCR_X 0
#define ITEM_BOMB_SCR_Y 60
#define ITEM_CHEESE_SCR_X 18
#define ITEM_CHEESE_SCR_Y 165

#define SCENE_MAINMENU_SCR_X 480
#define SCENE_MAINMENU_SCR_Y 270
#define SCENE_BOSS_SCR_X 480
#define SCENE_BOSS_SCR_Y 200
#define SCENE_BOSS_ENTER_SCR_Y 960
#define SCENE_BOSS_ENTER_SCR_Y 150
#define SCENE_BOSS_ENTER_UP_SCR_Y 360
#define SCENE_BOSS_ENTER_UP_SCR_Y 50
#define SCENE_BOSS_ENTER_DOWN_SRC_Y 30

#define SCENE_MENU_SCR_W 200
#define SCENE_MENU_SCR_H 50

#define SCENE_MENU_START_POS_X 0
#define SCENE_MENU_START_POS_Y 600
#define SCENE_MENU_RESET_POS_X 0
#define SCENE_MENU_RESET_POS_Y 650
#define SCENE_MENU_EXIT_POS_X 0
#define SCENE_MENU_EXIT_POS_Y 700

#define SCENE_MAINMENU_POS_X 963
#define SCENE_MAINMENU_POS_Y 335
#define SCENE_BOSS_POS_X 0
#define SCENE_BOSS_POS_Y 220
#define SCENE_BOSS_ENTER_POS_X 512
#define SCENE_BOSS_ENTER_POS_Y 8
#define SCENE_BOSS_ENTER_UP_POS_Y 1110
#define SCENE_BOSS_ENTER_UP_POS_Y 180
#define SCENE_BOSS_ENTER_DOWN_POS_Y 1170
#define SCENE_BOSS_ENTER_DOWN_POS_Y 225

#define EFFECT_LONGSWORD_SCR_X 23
#define EFFECT_LONGSWORD_SCR_Y 66
#define EFFECT_LONGSWORD_POS_X 17
#define EFFECT_LONGSWORD_POS_Y 327

#define EFFECT_DAGGER_SCR_X 23
#define EFFECT_DAGGER_SCR_Y 15
#define EFFECT_DAGGER_POS_X 297
#define EFFECT_DAGGER_POS_Y 109

#define EFFECT_RAPIER_SCR_X 38
#define EFFECT_RAPIER_SCR_Y 11
#define EFFECT_RAPIER1_POS_X 379
#define EFFECT_RAPIER2_POS_X 436
#define EFFECT_RAPIER3_POS_X 487
#define EFFECT_RAPIER4_POS_X 535
#define EFFECT_RAPIER_POS_Y 85

#define EFFECT_ICE_SCR_X 42
#define EFFECT_ICE_SCR_Y 27
#define EFFECT_ICE_POS_X 0
#define EFFECT_ICE_POS_Y 16

#define EFFECT_BOMB_SCR_X 75
#define EFFECT_BOMB_SCR_Y 78
#define EFFECT_BOMB_POS_X 105
#define EFFECT_BOMB_POS_Y 243

#define EFFECT_ENEMY_ATTACK_SCR_X 30
#define EFFECT_ENEMY_ATTACK_SCR_X 24
#define EFFECT_ENEMY_ATTACK_POS_X 589
#define EFFECT_ENEMY_ATTACK_POS_Y 165

#define SPRITEPATH_FLOORS       L"Sprite/Floor/Floors.png"
#define SPRITEPATH_WALLS        L"Sprite/Floor/Walls.png"

#define SPRITEPATH_CHARACTERS   L"Sprite/Characters.png"
#define SPRITEPATH_SLIMES       L"Sprite/Monster/Monsters_Slimes.png"
#define SPRITEPATH_WRAITHS      L"Sprite/Monster/Monsters_Wraiths.png"
#define SPRITEPATH_SKELETONS    L"Sprite/Monster/Monsters_Skeletons.png"
#define SPRITEPATH_BAT    L"Sprite/Monster/Monster_Bats.png"
#define SPRITEPATH_DRAGONS      L"Sprite/Monster/Monsters_Dragons.png"
#define SPRITEPATH_MINOTAURS    L"Sprite/Monster/Monsters_Minotaurs.png"
#define SPRITEPATH_KINGCONGA    L"Sprite/Monster/Monster_Boss_KingConga.png"
#define SPRITEPATH_SHOPKEPPER   L"Sprite/NPC/NPC_Shopkeeper.png"

#define SPRITEPATH_EFFECT_ATTACK	L"Sprite/Effect/Effects_Attack.png"
#define SPRITEPATH_EFFECT_SPELLS L"Sprite/Effect/Effects_Spells.png"

#define SPRITEPATH_SCENE_BOSS   L"Sprite/Scene/Scene_Boss.png"
#define SPRITEPATH_SCENE_TITLE  L"Sprite/Scene/Scene_Title.png"

#define SPRITEPATH_ARMOR        L"Sprite/Item/items_Armor.png"
#define SPRITEPATH_CONSUMABLES  L"Sprite/Item/items_Consumables.png"
#define SPRITEPATH_FOOTWEAR     L"Sprite/Item/items_Footwear.png"
#define SPRITEPATH_HEADWEAR		L"Sprite/Item/items_Headwear.png"
#define SPRITEPATH_RESOURCES	L"Sprite/Item/items_Resources.png"
#define SPRITEPATH_SHOVELS		L"Sprite/Item/items_Shovels.png"
#define SPRITEPATH_TORCHES		L"Sprite/Item/items_Torches.png"
#define SPRITEPATH_WEAPONS		L"Sprite/Item/items_Weapons.png"
#define SPRITEPATH_SPEELS		L"Sprite/Item/Items_Spells.png"

#define SPRITEPATH_HUD			L"Sprite/Ui/HUD.png"



enum SceneType {
	SCENE_TITLE,
	SCENE_INGAME,
	SCENE_BOSS
};

enum TileType
{
	TILE_EMPTY = 0,
	TILE_WALL_DEFAULT,
	TILE_WALL_HARD,
	TILE_WALL_BADROCK,
	TILE_WALL_SHOP,
	TILE_FLOOR
};

enum Visibility {
	VIS_HIDDEN,
	VIS_EXPLORED,
	VIS_VISIBLE
};

enum ItemID {
	ITEM_NONE,
	ITEM_DAGGER,
	ITEM_LONGSWORD,
	ITEM_TORCH_BASIC,
	ITEM_TORCH_BRIGHT,
	ITEM_ARMOR_LEATHER,
	ITEM_ARMOR_CHAINMAIL,
	ITEM_ARMOR_PLATE,
	ITEM_SHOVEL_IRON,
	ITEM_SHOVEL_GOLD,
	ITEM_SHOVEL_TITANIUM,
	ITEM_GLASS_SWORD,
	ITEM_RAPIER,
	ITEM_FOOTWEAR_BASIC,
	ITEM_HEADWEAR_BASIC,
	ITEM_GOLD_COIN,
	ITEM_BOMB,
	ITEM_CHEESE,
	ITEM_COUNT
};

enum AbilityTrigger {
	TRIGGER_ON_ATTACK,
	TRIGGER_ON_DAMAGED,
	TRIGGER_ON_MOVE,
	TRIGGER_ON_DIG,
	TRIGGER_ON_KILL
};

enum ItemSlot {
	SLOT_WEAPON,
	SLOT_HEAD,
	SLOT_BODY,
	SLOT_FEET,
	SLOT_SHOVEL,
	SLOT_TORCH,
	SLOT_ACCESSORY,
	SLOT_CONSUMABLE,
	SLOT_COUNT
};

enum ItemMaterial {
	MAT_BASE,
	MAT_OBSIDIAN,
	MAT_GLASS,
	MAT_GOLD,
	MAT_BLOOD,
	MAT_TITANIUM
};

